services:
  # Client - React (Vite)
  client:
    build:
      context: ./PlotWeaver
    env_file:
      - .env
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./PlotWeaver:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - plotweaver-network

  # Backend - Spring Boot API
  server:
    build:
      context: ./plotweaverback/plotweaver-api

    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./plotweaverback/plotweaver-api:/workspace
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SECURITY_USER_NAME=${SPRING_SECURITY_USER_NAME}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD}
      - SPRING_SECURITY_USER_ROLES=${SPRING_SECURITY_USER_ROLES}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - plotweaver-network

  # Database - MySQL
  db:
    image: mysql:8.0-debian
    container_name: plotweaver-db
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: unless-stopped
    networks:
      - plotweaver-network

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: plotweaver-phpmyadmin
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=${MYSQL_PORT}
      - PMA_USER=${MYSQL_USER}
      - PMA_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - plotweaver-network

volumes:
  db_data:
    driver: local

networks:
  plotweaver-network:
    driver: bridge